### ISSUE TITLE
Not able to locate scala.XML while adding 2.1.0.Beta3 version in dependency

### ISSUE THREAD

**Issue by deepakas** [elasticsearch/elasticsearch-hadoop#374] opened 2015-02-07 15:55 UTC
I was able to process XML in spark using scala.xml.XML class. For some reason once I add the elasticsearch-hadoop version 2.1.0.Beta3  in mvn as a dependency it is not able to recognize the scala.xml class in the project. Any thoughts ?

Error:(2, 14) object xml is not a member of package scala
import scala.xml.XML
             ^

**Comment by costin** [comment] 2015-02-07 16:25
Sorry, no. Better ask maven: `mvn dependency:dependency` and see what happens to `scala.xml.XML`

**Comment by costin** [comment] 2015-02-07 16:31
Just looked into the dependencies - considering `scala.xml` is part of the Scala package most likely you are not adding scala/spark/es-hadoop to `compile` scope and potentially use it only at `runtime`. A guess that in other words, you are telling Maven to use Scala when running your code not when it compiles it.

**Comment by deepakas** [comment] 2015-02-07 16:44
Thanks Costin for checking. It finds the scala.xml package class when
I use 2.1.0.Beta1
but not with 2.1.0.Beta2 or 2.1.0.Beta3. When I use 2.1.0.Beta1 I am
getting another error. I am looking into the dependency.

15/02/07 16:43:15 INFO Slf4jLogger: Slf4jLogger started
Exception in thread "main" java.lang.ClassNotFoundException:
com.google.protobuf_spark.GeneratedMessage

On Sat, Feb 7, 2015 at 4:31 PM, Costin Leau <notifications@github.com>
wrote:

> Just looked into the dependencies - considering scala.xml is part of the
> Scala package most likely you are not adding scala/spark/es-hadoop to
> compile scope and potentially use it only at runtime. A guess that in
> other words, you are telling Maven to use Scala when running your code not
> when it compiles it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch-hadoop/issues/374#issuecomment-73371115>
> .
>



-- 
Deepak Subhramanian

**Comment by deepakas** [comment] 2015-02-08 17:34
I was able to resolve the ClassNotFoundException by adding this exclusion.
I am using spark-core_2.11 with 1.2.0 version.

15/02/07 16:43:15 INFO Slf4jLogger: Slf4jLogger started
Exception in thread "main" java.lang.ClassNotFoundException:
com.google.protobuf_spark.GeneratedMessage

<dependency>
    <groupId>org.elasticsearch</groupId>
    <artifactId>elasticsearch-hadoop</artifactId>
    <version>2.1.0.Beta1</version>
    <exclusions>
        <exclusion>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.10</artifactId>
    </exclusion>
    </exclusions>
</dependency>


On Sat, Feb 7, 2015 at 4:44 PM, Deepak Subhramanian <
deepak.subhramanian@gmail.com> wrote:

> Thanks Costin for checking. It finds the scala.xml package class when I
> use 2.1.0.Beta1 but not with 2.1.0.Beta2 or 2.1.0.Beta3. When I use
> 2.1.0.Beta1 I am getting another error. I am looking into the dependency.
>
> 15/02/07 16:43:15 INFO Slf4jLogger: Slf4jLogger started
> Exception in thread "main" java.lang.ClassNotFoundException:
> com.google.protobuf_spark.GeneratedMessage
>
> On Sat, Feb 7, 2015 at 4:31 PM, Costin Leau <notifications@github.com>
> wrote:
>
>> Just looked into the dependencies - considering scala.xml is part of the
>> Scala package most likely you are not adding scala/spark/es-hadoop to
>> compile scope and potentially use it only at runtime. A guess that in
>> other words, you are telling Maven to use Scala when running your code not
>> when it compiles it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/elasticsearch/elasticsearch-hadoop/issues/374#issuecomment-73371115>
>> .
>>
>
>
>
> --
> Deepak Subhramanian
>



-- 
Deepak Subhramanian

**Comment by costin** [comment] 2015-02-09 18:27
@deepakas It looks like the issue is caused by using Spark compiled against Scala 2.11 while es-hadoop/spark relies on Spark compiled with Scala 2.10 (that's what the official release anyway).
I've created an issue (##376) to provide a 2.11 compatible release for the es-spark jar; es-hadoop will likely remain on Scala 2.10 as 2.11 seems to be added only since 1.2.0 and is not yet fully supported.

Closing this issue.

P.S. By the way, if you use only the spark module, you can also opt for elasticsearch-spark module instead.

**Closed by costin** 2015-02-09 18:27 UTC

**Comment by deepakas** [comment] 2015-02-09 18:36
Hi Costin,

Thank you very much for the clarification and suggestion. I will use the
spark version  in elasticsearch-hadoop .

Thanks, Deepak

On Mon, Feb 9, 2015 at 6:27 PM, Costin Leau <notifications@github.com>
wrote:

> @deepakas <https://github.com/deepakas> It looks like the issue is caused
> by using Spark compiled against Scala 2.11 while es-hadoop/spark relies on
> Spark compiled with Scala 2.10 (that's what the official release anyway).
> I've created an issue (##376
> <https://github.com/elasticsearch/elasticsearch-hadoop/issues/376>) to
> provide a 2.11 compatible release for the es-spark jar; es-hadoop will
> likely remain on Scala 2.10 as 2.11 seems to be added only since 1.2.0 and
> is not yet fully supported.
>
> Closing this issue.
>
> P.S. By the way, if you use only the spark module, you can also opt for
> elasticsearch-spark module instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch-hadoop/issues/374#issuecomment-73561718>
> .
>



-- 
Deepak Subhramanian

**Comment by costin** [comment] 2015-02-09 20:45
@deepakas I've pushed a dev build for 2.11 - you can find it maven already (see the docs - the install chapter). Can you please try it out and let me know how it works for you? Let's continue the discussion on #376 - thanks!
