### ISSUE TITLE
TaskAttemptId string is not properly formed

### ISSUE THREAD

**Issue by ujlim** [elasticsearch/elasticsearch-hadoop#346] opened 2014-12-26 10:10 UTC
I've done INSERT-TO-ES with Hadoop 2.4.0 and es-hadoop 2.0.2 or 2.1.0.Beta3, ES 1.4.1.
```sql
CREATE EXTERNAL TABLE es_201409_test (
    mailguid          STRING,
    mailtextcontent   STRING,
    mailtimereceived  STRING,
    mailtimesent      STRING
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = '201409/test','es.nodes' = '10.0.53.26','es.port' = '9201', 'es.query' = '?q=*', 'es.mapping.id' = 'mailguid');

INSERT OVERWRITE TABLE es_201409_test 
select guid as mailguid,
       portdesc as mailtextcontent,
       rcvtime  as mailtimereceived,
       rcvtime  as mailtimesent       
from 	
ism_tb_ods_XXXX limit 10;
```
But I've met "TaskAttemptId string: task1419585839976_0003_r_000000_2 is not properly formed".
I guess that as like "task_1419567106175_0509_m_000000" is right.

How can I do to solve this problem? 

 ---------------------- Running Log -----------------------------------
```
Container released by application, AttemptID:attempt_1419585839976_0003_1_00_000000_2 Info:Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":"7F9D9782-B248-E411-9628-001517EB0FA5","_col1":"*.google.com","_col2":"2014-10-01 00:00:33.0","_col3":"2014-10-01 00:00:33.0"}}
        at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.processKeyValues(ReduceRecordProcessor.java:344)
        at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.run(ReduceRecordProcessor.java:223)
        at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.run(TezProcessor.java:164)
        at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:307)
        at org.apache.hadoop.mapred.YarnTezDagChild$5.run(YarnTezDagChild.java:562)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapred.YarnTezDagChild.main(YarnTezDagChild.java:551)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":"7F9D9782-B248-E411-9628-001517EB0FA5","_col1":"*.google.com","_col2":"2014-10-01 00:00:33.0","_col3":"2014-10-01 00:00:33.0"}}
        at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.processKeyValues(ReduceRecordProcessor.java:329)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: TaskAttemptId string : task1419585839976_0003_r_000000_2 is not properly formed
        at org.apache.hadoop.mapreduce.TaskAttemptID.forName(TaskAttemptID.java:201)
        at org.apache.hadoop.mapred.TaskAttemptID.forName(TaskAttemptID.java:129)
        at org.elasticsearch.hadoop.mr.HadoopCfgUtils.getTaskID(HadoopCfgUtils.java:148)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.detectCurrentInstance(EsOutputFormat.java:263)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:164)
        at org.elasticsearch.hadoop.hive.EsHiveOutputFormat$EsHiveRecordWriter.write(EsHiveOutputFormat.java:58)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.processOp(FileSinkOperator.java:621)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
        at org.apache.hadoop.hive.ql.exec.LimitOperator.processOp(LimitOperator.java:51)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
        at org.apache.hadoop.hive.ql.exec.ExtractOperator.processOp(ExtractOperator.java:45)
        at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.processKeyValues(ReduceRecordProcessor.java:320)
        ... 8 more

Container released by application, AttemptID:attempt_1419585839976_0003_1_00_000000_3 Info:Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":"7F9D9782-B248-E411-9628-001517EB0FA5","_col1":"*.google.com","_col2":"2014-10-01 00:00:33.0","_col3":"2014-10-01 00:00:33.0"}}
        at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.processKeyValues(ReduceRecordProcessor.java:344)
        at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.run(ReduceRecordProcessor.java:223)
        at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.run(TezProcessor.java:164)
        at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:307)
        at org.apache.hadoop.mapred.YarnTezDagChild$5.run(YarnTezDagChild.java:562)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapred.YarnTezDagChild.main(YarnTezDagChild.java:551)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":"7F9D9782-B248-E411-9628-001517EB0FA5","_col1":"*.google.com","_col2":"2014-10-01 00:00:33.0","_col3":"2014-10-01 00:00:33.0"}}
        at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.processKeyValues(ReduceRecordProcessor.java:329)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: TaskAttemptId string : task1419585839976_0003_r_000000_3 is not properly formed
        at org.apache.hadoop.mapreduce.TaskAttemptID.forName(TaskAttemptID.java:201)
        at org.apache.hadoop.mapred.TaskAttemptID.forName(TaskAttemptID.java:129)
        at org.elasticsearch.hadoop.mr.HadoopCfgUtils.getTaskID(HadoopCfgUtils.java:148)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.detectCurrentInstance(EsOutputFormat.java:263)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:164)
        at org.elasticsearch.hadoop.hive.EsHiveOutputFormat$EsHiveRecordWriter.write(EsHiveOutputFormat.java:58)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.processOp(FileSinkOperator.java:621)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
        at org.apache.hadoop.hive.ql.exec.LimitOperator.processOp(LimitOperator.java:51)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
        at org.apache.hadoop.hive.ql.exec.ExtractOperator.processOp(ExtractOperator.java:45)
        at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordProcessor.processKeyValues(ReduceRecordProcessor.java:320)
        ... 8 more
], Vertex failed as one or more tasks failed. failedTasks:1]
2014-12-26 18:55:10,273 ERROR tez.TezJobMonitor (SessionState.java:printError(545)) - DAG failed due to vertex failure. failedVertices:1 killedVertices:0
2014-12-26 18:55:10,274 INFO  log.PerfLogger (PerfLogger.java:PerfLogEnd(135)) - </PERFLOG method=TezRunDag start=1419587687599 end=1419587710274 duration=22675 from=org.apache.hadoop.hive.ql.exec.tez.TezJobMonitor>
2014-12-26 18:55:10,278 INFO  exec.Task (TezTask.java:execute(179)) - org.apache.tez.common.counters.DAGCounter:
2014-12-26 18:55:10,278 INFO  exec.Task (TezTask.java:execute(181)) -    NUM_FAILED_TASKS: 4
2014-12-26 18:55:10,278 INFO  exec.Task (TezTask.java:execute(181)) -    TOTAL_LAUNCHED_TASKS: 5
2014-12-26 18:55:10,278 INFO  exec.Task (TezTask.java:execute(181)) -    DATA_LOCAL_TASKS: 1
2014-12-26 18:55:10,279 INFO  exec.Task (TezTask.java:execute(179)) - File System Counters:
2014-12-26 18:55:10,279 INFO  exec.Task (TezTask.java:execute(181)) -    FILE: BYTES_READ: 32
2014-12-26 18:55:10,279 INFO  exec.Task (TezTask.java:execute(181)) -    FILE: BYTES_WRITTEN: 399
2014-12-26 18:55:10,279 INFO  exec.Task (TezTask.java:execute(181)) -    FILE: READ_OPS: 0
2014-12-26 18:55:10,279 INFO  exec.Task (TezTask.java:execute(181)) -    FILE: LARGE_READ_OPS: 0
2014-12-26 18:55:10,279 INFO  exec.Task (TezTask.java:execute(181)) -    FILE: WRITE_OPS: 0
2014-12-26 18:55:10,280 INFO  exec.Task (TezTask.java:execute(181)) -    HDFS: BYTES_READ: 131072
2014-12-26 18:55:10,280 INFO  exec.Task (TezTask.java:execute(181)) -    HDFS: BYTES_WRITTEN: 0
2014-12-26 18:55:10,280 INFO  exec.Task (TezTask.java:execute(181)) -    HDFS: READ_OPS: 1
2014-12-26 18:55:10,280 INFO  exec.Task (TezTask.java:execute(181)) -    HDFS: LARGE_READ_OPS: 0
2014-12-26 18:55:10,280 INFO  exec.Task (TezTask.java:execute(181)) -    HDFS: WRITE_OPS: 0
2014-12-26 18:55:10,280 INFO  exec.Task (TezTask.java:execute(179)) - org.apache.tez.common.counters.TaskCounter:
2014-12-26 18:55:10,281 INFO  exec.Task (TezTask.java:execute(181)) -    SPILLED_RECORDS: 10
2014-12-26 18:55:10,281 INFO  exec.Task (TezTask.java:execute(181)) -    GC_TIME_MILLIS: 0
2014-12-26 18:55:10,281 INFO  exec.Task (TezTask.java:execute(181)) -    CPU_MILLISECONDS: -1030
2014-12-26 18:55:10,281 INFO  exec.Task (TezTask.java:execute(181)) -    PHYSICAL_MEMORY_BYTES: 1358917632
2014-12-26 18:55:10,281 INFO  exec.Task (TezTask.java:execute(181)) -    VIRTUAL_MEMORY_BYTES: 2759393280
2014-12-26 18:55:10,282 INFO  exec.Task (TezTask.java:execute(181)) -    COMMITTED_HEAP_BYTES: 1852833792
2014-12-26 18:55:10,282 INFO  exec.Task (TezTask.java:execute(181)) -    INPUT_RECORDS_PROCESSED: 15
2014-12-26 18:55:10,282 INFO  exec.Task (TezTask.java:execute(181)) -    OUTPUT_RECORDS: 10
2014-12-26 18:55:10,282 INFO  exec.Task (TezTask.java:execute(181)) -    OUTPUT_BYTES: 1115
2014-12-26 18:55:10,282 INFO  exec.Task (TezTask.java:execute(181)) -    OUTPUT_BYTES_WITH_OVERHEAD: 1137
2014-12-26 18:55:10,283 INFO  exec.Task (TezTask.java:execute(181)) -    OUTPUT_BYTES_PHYSICAL: 367
2014-12-26 18:55:10,283 INFO  exec.Task (TezTask.java:execute(181)) -    ADDITIONAL_SPILLS_BYTES_WRITTEN: 0
2014-12-26 18:55:10,283 INFO  exec.Task (TezTask.java:execute(181)) -    ADDITIONAL_SPILLS_BYTES_READ: 0
2014-12-26 18:55:10,283 INFO  exec.Task (TezTask.java:execute(181)) -    ADDITIONAL_SPILL_COUNT: 0
2014-12-26 18:55:10,283 INFO  exec.Task (TezTask.java:execute(179)) - org.apache.hadoop.hive.ql.exec.MapOperator$Counter:
2014-12-26 18:55:10,284 INFO  exec.Task (TezTask.java:execute(181)) -    DESERIALIZE_ERRORS: 0
2014-12-26 18:55:10,288 ERROR ql.Driver (SessionState.java:printError(545)) - FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask
2014-12-26 18:55:10,288 INFO  log.PerfLogger (PerfLogger.java:PerfLogEnd(135)) - </PERFLOG method=Driver.execute start=1419587682970 end=1419587710288 duration=27318 from=org.apache.hadoop.hive.ql.Driver>
2014-12-26 18:55:10,288 INFO  log.PerfLogger (PerfLogger.java:PerfLogBegin(108)) - <PERFLOG method=releaseLocks from=org.apache.hadoop.hive.ql.Driver>
2014-12-26 18:55:10,289 INFO  log.PerfLogger (PerfLogger.java:PerfLogEnd(135)) - </PERFLOG method=releaseLocks start=1419587710288 end=1419587710289 duration=1 from=org.apache.hadoop.hive.ql.Driver>
2014-12-26 18:55:10,289 ERROR operation.Operation (SQLOperation.java:run(202)) - Error running hive query: 
org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask
        at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:146)
        at org.apache.hive.service.cli.operation.SQLOperation.access$000(SQLOperation.java:68)
        at org.apache.hive.service.cli.operation.SQLOperation$1$1.run(SQLOperation.java:199)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.hive.shims.HadoopShimsSecure.doAs(HadoopShimsSecure.java:493)
        at org.apache.hive.service.cli.operation.SQLOperation$1.run(SQLOperation.java:208)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2014-12-26 18:55:10,296 INFO  log.PerfLogger (PerfLogger.java:PerfLogBegin(108)) - <PERFLOG method=releaseLocks from=org.apache.hadoop.hive.ql.Driver>
2014-12-26 18:55:10,297 INFO  log.PerfLogger (PerfLogger.java:PerfLogEnd(135)) - </PERFLOG method=releaseLocks start=1419587710296 end=1419587710297 duration=1 from=org.apache.hadoop.hive.ql.Driver>
2014-12-26 18:55:10,297 INFO  tez.TezSessionPoolManager (TezSessionPoolManager.java:close(172)) - Closing tez session default? false
2014-12-26 18:55:10,297 INFO  tez.TezSessionState (TezSessionState.java:close(240)) - Closing Tez Session
2014-12-26 18:55:10,298 INFO  client.TezSession (TezSession.java:stop(257)) - Shutting down Tez Session, sessionName=HIVE-4c86a474-9029-48e6-8403-b4ae94d7d3de, applicationId=application_1419585839976_0003
2014-12-26 18:57:06,967 INFO  exec.TableScanOperator (Operator.java:close(574)) - 0 finished. closing... 
2014-12-26 18:57:06,967 INFO  exec.SelectOperator (Operator.java:close(574)) - 1 finished. closing... 
2014-12-26 18:57:06,967 INFO  exec.ListSinkOperator (Operator.java:close(574)) - 3 finished. closing... 
2014-12-26 18:57:06,968 INFO  exec.ListSinkOperator (Operator.java:close(591)) - 3 Close done
2014-12-26 18:57:06,968 INFO  exec.SelectOperator (Operator.java:close(591)) - 1 Close done
2014-12-26 18:57:06,968 INFO  exec.TableScanOperator (Operator.java:close(591)) - 0 Close done
2014-12-26 18:57:06,978 INFO  log.PerfLogger (PerfLogger.java:PerfLogBegin(108)) - <PERFLOG method=releaseLocks from=org.apache.hadoop.hive.ql.Driver>
2014-12-26 18:57:06,979 INFO  log.PerfLogger (PerfLogger.java:PerfLogEnd(135)) - </PERFLOG method=releaseLocks start=1419587826978 end=1419587826979 duration=1 from=org.apache.hadoop.hive.ql.Driver>
```

**Comment by costin** [comment] 2015-01-06 14:42
Hi,

I've pushed a fix (the artifacts are uploaded) that tries to workaround the invalid Tez string. Can you please try it and report back? Also please keep an eye on the logs to see whether you see any warnings in there...

**Comment by costin** [comment] 2015-01-06 14:43
@ujlim FTR, the dev artifacts can be found in Maven - see [this section](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/install.html#download-dev) of the reference documentation

**Comment by ujlim** [comment] 2015-01-07 09:27
I need sometime to do other things before trying your fix. But I'll go as soon as possible!! Thank you.

**Comment by costin** [comment] 2015-01-12 14:09
@ujlim any update? Thanks!

**Comment by costin** [comment] 2015-01-15 12:20
Closing the issue...

**Closed by costin** 2015-01-15 12:20 UTC
Labels: enhancement, hive, v2.0.3, v2.1.0.Beta4

**Comment by srikanth0863** [comment] 2015-07-07 09:40
When i try to run hive query using beeline, and through java this is the exception:
Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask; nested exception is java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:413)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:468)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:478)
        at org.clinical3PO.services.data.dao.PatientSearchDAO.printPatientDeatils(PatientSearchDAO.java:66)
        at org.clinical3PO.services.PatientSearchService.getPatientSearchOnHiveQL(PatientSearchService.java:26)
        at org.clinical3PO.services.hive.HiveSearchEngine.main(HiveSearchEngine.java:52)
Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask
        at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:161)
        at org.apache.hive.jdbc.Utils.verifySuccessWithInfo(Utils.java:149)
        at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:182)
        at org.apache.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:246)
        at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:452)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:402)
        ... 5 more
[ERROR] 2015-07-07 05:31:27,896 org.clinical3PO.services.hive.HiveSearchEngine main -
org.springframework.dao.DataAccessResourceFailureException: StatementCallback; SQL [SELECT concept.property_name, observation.observation_date, observation.observation_time, observation.value_as_number, concept.value_units FROM omopv4demo.observation JOIN omopv4demo.concept ON (observation.observation_concept_id = concept.src_concept_id) WHERE observation.person_id=142106]; Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask; nested exception is java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:413)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:468)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:478)
        at org.clinical3PO.services.data.dao.PatientSearchDAO.printPatientDeatils(PatientSearchDAO.java:66)
        at org.clinical3PO.services.PatientSearchService.getPatientSearchOnHiveQL(PatientSearchService.java:26)
        at org.clinical3PO.services.hive.HiveSearchEngine.main(HiveSearchEngine.java:52)
Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask
        at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:161)
        at org.apache.hive.jdbc.Utils.verifySuccessWithInfo(Utils.java:149)
        at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:182)
        at org.apache.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:246)
        at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:452)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:402)
        ... 5 more
