### ISSUE TITLE
elasticsearch-spark_2.10-2.1.0.Beta2 exception when join with parqustFile

### ISSUE THREAD

**Issue by huangchen007** [elasticsearch/elasticsearch-hadoop#323] opened 2014-11-19 20:06 UTC
I got exception like below when i worked on spark sql join 

Seems to serialiation problem.

Class cannot be created (missing no-arg constructor): ScalaEsRow

**Comment by costin** [comment] 2015-01-12 14:09
@huangchen007 Hi, did you manage to test master ?

**Comment by costin** [comment] 2015-01-15 12:22
As there hasn't been any update and I couldn't reproduce the issue, I'm closing it down. If it keeps on occurring, please open up a new issue.

**Closed by costin** 2015-01-15 12:22 UTC
Labels: bug, spark, v2.1.0.Beta4
